# values-demo.yaml - k3d Environment Overlay
# This overlay overrides specific settings from values.yaml for the demo environment running on k3d.

image:
  repository: 'ghcr.io/duytrq/demo-app'
  tag: 'latest'
  digest: 'sha256:009767c6faec453a2904f675b93c84d62df360a61408e6797f29688a4c793383'
  pullSecrets: []
app:
  replicas: 1
  existingSecret: demo-app-db
podDisruptionBudget:
  enabled: false
  minAvailable: 1
postgres:
  existingSecret: demo-app-db
  storage:
    createStorageClass: false
    className: local-path
    size: 2Gi
ingress:
  enabled: true
  className: traefik
  host: 'demo.localhost'
vault:
  enabled: true
  address: 'https://46.137.235.153:8200/'
  role: 'demo-app'
  secretPath: 'jits/demo-app/stg/db'
  caSecretName: 'vault-ca-cert'
