replicaCount: 3

ingress:
  host: canary-demo.local

image:
  repository: argoproj/rollouts-demo
  tag: blue
  pullPolicy: IfNotPresent
  containerPort: 8080

service:
  type: ClusterIP
  port: 80

analysis:
  enabled: true
  prometheusAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
  errorRateThreshold: '0.05'
  interval: 30s
  count: 5
  failureLimit: 1

canary:
  steps:
    - weight: 10
      pauseDuration: 60s
    - weight: 30
      pauseDuration: 60s
    - weight: 60
      pauseDuration: 60s
