{{- if .Values.analysis.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ template "canary-demo.fullname" . }}-error-rate
  labels:
    {{- include "canary-demo.labels" . | nindent 4 }}
spec:
  args:
    - name: ingress-name
  metrics:
    - name: error-rate
      interval: {{ .Values.analysis.interval }}
      count: {{ .Values.analysis.count }}
      successCondition: "len(result) == 0 || result[0] < {{ .Values.analysis.errorRateThreshold }}"
      failureLimit: {{ .Values.analysis.failureLimit }}
      provider:
        prometheus:
          address: {{ .Values.analysis.prometheusAddress }}
          query: |
            sum(rate(
              nginx_ingress_controller_requests{ingress="{{ "{{args.ingress-name}}" }}",namespace="canary",status=~"5.."}[1m]
            )) /
            sum(rate(
              nginx_ingress_controller_requests{ingress="{{ "{{args.ingress-name}}" }}",namespace="canary"}[1m]
            ))
{{- end }}
