{{- if .Values.analysis.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "canary-demo.fullname" . }}
  labels:
    {{- include "canary-demo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "canary-demo.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
