{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "demo-app.fullname" . }}-vault
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.address | quote }}
      path: {{ .Values.vault.kvMountPath | quote }}
      version: "v2"
      {{- if .Values.vault.caSecretName }}
      caProvider:
        type: Secret
        name: {{ .Values.vault.caSecretName | quote }}
        key: {{ .Values.vault.caSecretKey | default "ca.crt" | quote }}
      {{- end }}
      auth:
        appRole:
          path: {{ .Values.vault.appRole.authPath | quote }}
          roleRef:
            name: {{ .Values.vault.appRole.secretName | quote }}
            key: {{ .Values.vault.appRole.roleIdKey | quote }}
          secretRef:
            name: {{ .Values.vault.appRole.secretName | quote }}
            key: {{ .Values.vault.appRole.secretIdKey | quote }}
{{- end }}
