{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.existingSecret }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.vault.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ include "demo-app.fullname" . }}-vault
    kind: SecretStore
  target:
    name: {{ .Values.app.existingSecret }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    {{- range .Values.vault.secretKeys }}
    - secretKey: {{ .kubeKey }}
      remoteRef:
        key: {{ $.Values.vault.secretPath }}
        property: {{ .vaultKey }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    {{- end }}
{{- end }}

